dataset:
  train_dataset: "../data/demo/benign_train.csv"
  validation_dataset: "../data/demo/benign_test.csv"
  test_dataset: ""

train:
  optimizer: "Adam"
  lr: 1e-3
  batch_size: 1000
  epochs: 1000

  scheduler:
    active: "True"
    patience: 10


save:
  model: "../experiments/"
  every: 10