dataset:
  train_dataset: "../data/demo/benign_train.csv"
  validation_dataset: "../data/demo/benign_test.csv"
  test_dataset: "../data/demo/syn_attack.csv"
  __test_dataset: "../data/full_dataset/SimpleHome_XCS7_1002_WHT_Security_Camera/benign_traffic.csv"
  _test_dataset: "../data/full_dataset/SimpleHome_XCS7_1002_WHT_Security_Camera/mirai_attacks/udp.csv"

train:
  optimizer: "Adam"
  lr: 0.001
  batch_size: 1000
  epochs: 1000

  scheduler:
    active: "True"
    patience: 10


save:
  model: "../experiments/"
  every: 10