dataset:
  train_dataset_bob: "../data/demo_federated/Provision_PT_838_Security_Camera/benign_train.csv"
  train_dataset_alice: "../data/demo_federated/Provision_PT_737E_Security_Camera/benign_train.csv"

  validation_dataset_alice: "../data/demo_federated/Provision_PT_838_Security_Camera/benign_test.csv"
  validation_dataset_bob: "../data/demo_federated/Provision_PT_737E_Security_Camera/benign_test.csv"

  test_dataset: "../data/demo/syn_attack.csv"
  _test_dataset: "../data/full_dataset/SimpleHome_XCS7_1002_WHT_Security_Camera/mirai_attacks/udp.csv"

train:
  optimizer: "Adam"
  lr: 0.0001
  batch_size: 1000
  epochs: 10000

  scheduler:
    active: "True"
    patience: 10

save:
  model: "../experiments/"
  every: 10